### ISSUE TITLE
CommitDef.py is missing from repo

### ISSUE THREAD

**Issue by pansapiens** [monash-merc/mydata#36]
It would probably worth including this file with LATEST_COMMIT as an empty string. This would save confusion when working on fresh clones of the repo and help streamline setting up for development. It should still stay in .gitignore so changes don't get pushed back.

**Comment by wettenhj** [comment]
Hopefully this commit will make things easier:

https://github.com/monash-merc/mydata/commit/6c4268dcc58ed45bcc47ac096edf1123d5752eb7

**Comment by grischa** [comment]
But then you have a hard-to-access file in the repo. Wouldn't it be better to have the code that relies on this file not fail?

**Comment by wettenhj** [comment]
Grischa's approach sounds fine with me.

The same technique is used in Strudel, so whatever approach we come up
with, it would be good to share it with Chris.

**Comment by pansapiens** [comment]
Agree, Grischa's approach would be the preferred behaviour.
