### ISSUE TITLE
Pre-emptive uploads while checksumming for large files

### ISSUE THREAD

**Issue by keithschulze** [monash-merc/mydata#61]
MyData currently does MD5 checksum prior to commencing upload. For large files this can take quite a lot of time (~20 min for 96GB file). Would it be possible (at least for large files) to commence pre-emptive chunk uploads in the background while MD5 checksumming?

**Comment by wettenhj** [comment]
Good question.  Currently, MyData uses the MyTardis API's upload via staging method which requires creating a Datafile record before uploading, and the Datafile record creation requires an MD5 sum, assuming that MyTardis has REQUIRE_DATAFILE_CHECKSUMS = True in its settings.py.  Once the MD5 sum has been calculated and the Datafile record has been created, if you quit MyData and restart, then it won't need to recalculate the MD5 sum when resuming - it can reuse the one previously recorded in the Datafile record.

So maybe this MyData issue could be rephrased as a MyTardis API enhancement question?

**Comment by keithschulze** [comment]
Thanks for the update. I will open an issue on the MyTardis repo to see if there's a way around requiring the MD5 checksum to create a datafile record.

**Comment by wettenhj** [comment]
It looks like it is the save() method of MyTardis's Datafile model which checks the REQUIRE_DATAFILE_CHECKSUMS setting.  Maybe this check could be moved to the "verify" method?  That could cause some confusion for people who are used to the current meaning of this setting, but it could benefit staging uploads.  Feel free to copy this comment to the MyTardis issue if you create one.

**Comment by wettenhj** [comment]
As discussed in the linked MyTardis issue, a bogus checksum can be supplied by MyData when creating the Datafile record.  Some coding is required in MyData to fork the upload thread into two (MD5 sum and upload) and then wait until both are complete before using the MyTardis API's verify endpoint.
